# Generated by Django 5.1.3 on 2024-11-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_alter_video_video_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='file_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
